name = "ProportionalFitting"
uuid = "3c40d49d-59d4-4b5d-adaa-75a7fbc8c64f"
authors = ["Erik-Jan van Kesteren <erikjanvankesteren@pm.me>"]
version = "0.3.1"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
